/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddSheepBtnComponent: typeof import('./components/app/sheep/AddSheepBtnComponent.vue')['default']
    EmailVerifyComponent: typeof import('./components/app/dashboard/profile/EmailVerifyComponent.vue')['default']
    LocalePopselectComponent: typeof import('./components/common/LocalePopselectComponent.vue')['default']
    LoginFormComponent: typeof import('./components/app/Index/LoginFormComponent.vue')['default']
    MenubarComponent: typeof import('./components/common/MenubarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./components/Layouts/SidebarComponent.vue')['default']
    SignUpComponent: typeof import('./components/app/Index/SignUpComponent.vue')['default']
    ThemeSwichComponent: typeof import('./components/common/ThemeSwichComponent.vue')['default']
    UpdateProfileBtnComponent: typeof import('./components/app/profile/UpdateProfileBtnComponent.vue')['default']
  }
}
