/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LocalePopselectComponent: typeof import('./components/common/LocalePopselectComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./components/Layouts/SidebarComponent.vue')['default']
    ThemeSwichComponent: typeof import('./components/common/ThemeSwichComponent.vue')['default']
  }
}
